# 1. Create a 3x3x3 array with random values 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [6]:
data = np.random.random((3,3,3))
print(f"The shape of array is : {data.shape}")
print('\n',data)

The shape of array is : (3, 3, 3)

 [[[0.33035623 0.20933937 0.43808014]
  [0.90572497 0.46254424 0.74465619]
  [0.13591262 0.79284559 0.89709991]]

 [[0.57769182 0.65721859 0.91510842]
  [0.5777418  0.68625685 0.71788986]
  [0.25252776 0.62693244 0.80562736]]

 [[0.78091868 0.17028163 0.35586093]
  [0.76492428 0.72208111 0.36505379]
  [0.61703501 0.65175336 0.39781862]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [11]:
x = np.eye(5,5)
print(x)
x[1][0] = 1
x[2][1] = 2
x[3][2] = 3
x[4][3] = 4

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
x

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 2., 1., 0., 0.],
       [0., 0., 3., 1., 0.],
       [0., 0., 0., 4., 1.]])

# OR


In [137]:
x = np.diag(1+np.arange(4), k = -1)
print (x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [27]:
print("Checkerboard pattern:")
data = np.zeros((8,8),dtype=int)
data[1::2,::2] = 1
data[::2,1::2] = 1
print(data)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [29]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
print(f"\n The max value is : {xmax} and the min value is {xmin}")
x = (x - xmin)/(xmax - xmin)
print("\nAfter normalization:")
print(x)

Original Array:
[[0.48146029 0.41056467 0.09881197 0.35977279 0.73564142]
 [0.674353   0.74427222 0.55170668 0.9174469  0.383774  ]
 [0.54841418 0.0143097  0.54250052 0.77535238 0.17173952]
 [0.79208492 0.8367922  0.60582457 0.77049963 0.24094294]
 [0.62473679 0.75914265 0.35671692 0.29990578 0.65651629]]

 The max value is : 0.9174469014843082 and the min value is 0.014309695444259085

After normalization:
[[0.51725318 0.4387539  0.09356527 0.38251452 0.79869562]
 [0.73083392 0.80825208 0.5950336  1.         0.4090899 ]
 [0.59138798 0.         0.58484007 0.84266563 0.1743144 ]
 [0.86119276 0.91069496 0.65495572 0.83729242 0.25093999]
 [0.67589629 0.82471738 0.37913091 0.31622669 0.71108419]]


# 5.  How to find common values between two arrays?

In [30]:
data1 = np.array([0, 10, 20, 40, 60])
print("First Array is : ",data1)
data2 = [10, 30, 40]
print("Second Array is : ",data2)
print("Common values between two arrays :")
print(np.intersect1d(data1, data2))

First Array is :  [ 0 10 20 40 60]
Second Array is :  [10, 30, 40]
Common values between two arrays :
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [53]:
import datetime as dt
from datetime import *

x = dt.datetime.now()
print(x)

2020-07-26 12:31:00.777418


In [74]:
from datetime import date 
from datetime import *

In [78]:
today = date.today()
yesterday = today - timedelta(days = 1)
tomorrow = today +timedelta(days = 1) 
print('Yesterday : ',yesterday)
print('Today : ',today)
print('Tomorrow : ',tomorrow)

Yesterday :  2020-07-25
Today :  2020-07-26
Tomorrow :  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [98]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 1 0 0 0 1]
Second array:
[1 0 0 0 1 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [119]:
x = np.random.random(15)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0 :")
print(x)

Original array:
[0.42261538 0.70972145 0.32694454 0.45335543 0.63134346 0.93945091
 0.46334897 0.95611191 0.89932014 0.72226611 0.91371883 0.60406659
 0.16487633 0.02802511 0.91778205]
Maximum value replaced by 0 :
[0.42261538 0.70972145 0.32694454 0.45335543 0.63134346 0.93945091
 0.46334897 0.         0.89932014 0.72226611 0.91371883 0.60406659
 0.16487633 0.02802511 0.91778205]


# 9. How to print all the values of an array?

In [131]:
import numpy as np
np.set_printoptions(threshold=sys.maxsize)
x = np.random.random((4, 4))
print(x)

[[0.95732817 0.05920699 0.5542334  0.92561818]
 [0.77482495 0.15533748 0.88476555 0.39821792]
 [0.33089179 0.91696545 0.48494419 0.35051577]
 [0.45858878 0.98072652 0.89274307 0.83868546]]


# 10.Subtract the mean of each row of a matrix

In [135]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.15965038 0.33656146 0.66069988 0.3345265  0.1864836  0.49746706
  0.44821605 0.08450253 0.39675074 0.95860125]
 [0.31269332 0.02728166 0.88335092 0.11273902 0.48743019 0.14484812
  0.62177916 0.47954481 0.73086259 0.64792699]
 [0.9651683  0.58067401 0.95310791 0.12107939 0.58919533 0.28465157
  0.18145773 0.26465051 0.45162229 0.1745999 ]
 [0.8123177  0.86692752 0.17277026 0.28319518 0.59483788 0.25950333
  0.25268472 0.67968923 0.47050621 0.63286437]
 [0.43418286 0.7405758  0.73216621 0.59395184 0.37077178 0.30057415
  0.54214052 0.8323206  0.87205979 0.45463508]]

Subtract the mean of each row of the said matrix:

[[-0.24669557 -0.06978449  0.25435394 -0.07181945 -0.21986235  0.09112111
   0.04187011 -0.32184342 -0.0095952   0.5522553 ]
 [-0.13215236 -0.41756402  0.43850524 -0.33210666  0.04258451 -0.29999756
   0.17693348  0.03469913  0.28601691  0.20308131]
 [ 0.5085476   0.12405331  0.49648721 -0.3355413   0.13257464 -0.17196912
  -0.27516297 -0.19197018 -0.0

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [138]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)


[2. 4. 3. 3. 2. 4. 2. 3. 5. 2.]


# 12.How to get the diagonal of a dot product?

In [139]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
#Slow version

np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([ 94, 156,   9])

# 13.How to find the most frequent value in an array?

In [141]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[1 7 0 6 8 1 3 7 8 8 2 5 6 3 9 2 7 9 6 9 5 8 7 6 0 2 6 2 8 0 5 5 0 8 5 7 5
 5 5 1 9 3 9 6 7 7 8 3 0 8]
rank: 5


# 14.How to get the n largest values of an array

In [142]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9996 9999 9997 9995]


# 15.How to create a record array from a regular array?

In [143]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

In [144]:
print(Z)
print(R)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]
[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
